name: GitHub Release

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  github_release:
    if: |
      contains(github.event.head_commit.message, 'Automatic release') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout GIT
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '18'

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Get version from libs.versions.toml
        id: get_version
        run: |
          VERSION_NAME=$(grep 'version-name =' gradle/libs.versions.toml | awk -F'=' '{print $2}' | tr -d ' "')
          VERSION_CODE=$(grep 'version-code =' gradle/libs.versions.toml | awk -F'=' '{print $2}' | tr -d ' "')
          TAG_NAME="v$VERSION_NAME-$VERSION_CODE"
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Create and push tag
        run: |
          # Check if tag already exists
          if git rev-parse "${{ env.TAG_NAME }}" >/dev/null 2>&1; then
            echo "Tag ${{ env.TAG_NAME }} already exists, skipping tag creation"
          else
            git tag ${{ env.TAG_NAME }}
            git push origin ${{ env.TAG_NAME }}
            echo "Created and pushed tag ${{ env.TAG_NAME }}"
          fi

      - name: Build Demo APK
        run: ./gradlew assembleDemo

      - name: Upload APK to Github Actions
        uses: actions/upload-artifact@v4
        with:
          name: Ivy-Wallet-Demo.apk
          path: app/build/outputs/apk/demo/app-demo.apk

      - name: Prepare changelog for GitHub Release
        id: changelog
        continue-on-error: true
        uses: Bullrich/generate-release-changelog@master
        env:
          REPO: ${{ github.repository }}

      - name: Create GitHub Release
        id: create_github_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          body: |
            ${{ steps.changelog.outputs.changelog }}
            
            ## Download
            Download the APK from the assets below.
          draft: false
          prerelease: false
          files: app/build/outputs/apk/demo/app-demo.apk
          token: ${{ secrets.GITHUB_TOKEN }}
